In [ ]:
# 전역변수 목록 확인
%whos

##조건문

In [ ]:
score=input('점수: ')

In [ ]:
score

In [ ]:
type(score)

In [ ]:
%whos

In [ ]:
score=float(score)

In [ ]:
type(score)

In [ ]:
score

In [ ]:
score=float(input('점수는 '))

if score >= 90:
    print('합격')
elif score >= 80:
    print('재검사')
else:
    print('불합격')

##반복문

In [ ]:
menu=['짜장면', '짬뽕', '탕수육', '깐풍기', '난자완스']

In [ ]:
for item in menu:
    print(item, '시킬까요?', sep=',', end=' ')

In [ ]:
for item in menu:
    print(item, '시킬까요?')
    if item in ['짜장면','짬뽕']:
        print('--> 요리부터 주문합시다')
    print('--> 다음 메뉴는 뭔가요?\n')

### continue

In [ ]:
for item in menu:
    print(item, '시킬까요?')
    if item in ['짜장면','짬뽕']:
        continue
        print('--> 요리부터 주문합시다')
    print('--> 다음 메뉴는 뭔가요?\n')

### break

In [ ]:
for item in menu:
    print(item, '시킬까요?')
    if item in ['깐풍기']:
        break
        print('--> 요리부터 주문합시다')
    print('--> 다음 메뉴는 뭔가요?\n')

In [ ]:
#while loop와 break와 맞는다

## 중첩 반복문

In [ ]:
for i in range(2,10):
    print(f' *** {i}단 ***')
    for j in range(1,10):
        print(f'{i} X {j} = {i*j}')
    print() #단이 끝났을 때 한 칸 띄고 싶을 때

In [ ]:
sqrs=[]

for i in range(1,10):
    if i % 2 == 0:
        sqrs.append(i ** 2)
print(sqrs)

### 리스트 컴프리헨션

In [ ]:
[i ** 2 for i in range(1,10)]

In [ ]:
[i ** 2 for i in range(1,10) if i%2==0]

In [ ]:
[i ** 2 if i%2==0 else '홀수' for i in range(1,10)]

In [ ]:
#for i in range(2,10):
#    print(f' *** {i}단 ***')
#    for j in range(1,10):
#        print(f'{i} X {j} = {i*j}')

[f'{i} X {j} = {i*j}' for i in range(2,10) for j in range(1,10)]

## Zip 함수

In [ ]:
for i in zip(range(2,10), range(2,10)):
    print(i) #Tuple로 출력

In [ ]:
for i, j in zip(range(2,10), range(2,10)):
    print(i, j) #i, j를 쓰면 tuple을 풀어서 각 원소로 풀어줌

In [ ]:
for i, j in zip(range(2,10), range(2,10)):
    print(i+j)

In [ ]:
for i in enumerate(range(1,10)):
    print(i)

In [ ]:
for i, v in enumerate(range(1,10)):
    print(f'{i}의 인덱스는 {v}입니다')

## Try, Except

In [ ]:
for i in range(1,10):
    if i%3==0:
        i=str(i)
    try:
        print(i**2)
    except:
        print('에러발생')

In [ ]:
for i in range(1,10):
    if i%3==0:
        i=str(i)
    try:
        print(i**2)
    except Exception as e:
        print(e)

## while

In [ ]:
i=5
while i>0:
    print(i)
    i-=1

In [ ]:
i=0
while True:
    i+=1
    if i>=10000:
        break
print(i)

In [ ]:
# for loop은 반복 실행할 때 쓴다. 코드를 일부(변수)만 바꿔가면서 반복 실행할 때, 범위가 정해지면 for, 범위가 안정해지면 while 
# 1. 출력
# 2. 조건문 추가
# 3. continue, break
# 4. 중첩 반복문
# 5. 리스트로 남기는 것
# 6. zip함수, enumerate
# 7. 리스트 컴프리헨션
# 8. 예외처리

## 어제한 것 이어 하기

In [ ]:
import requests
from bs4 import BeautifulSoup as bts

In [ ]:
res=requests.get(url='https://finance.naver.com/item/main.naver?code=066570')

In [ ]:
res.status_code

In [ ]:
res.headers

In [ ]:
res.headers['content-type']

In [ ]:
len(res.text)

In [ ]:
res.text

In [ ]:
soup=bts(markup=res.text, features='html.parser')

In [ ]:
soup

In [ ]:
int(soup.select('p.no_today > em > span')[0].text.replace(',', ''))

In [ ]:
codes=['066570', '005930', '000660']

In [ ]:
for code in codes:
    res=requests.get(url=f'https://finance.naver.com/item/main.naver?code={code}')
    soup=bts(markup=res.text, features='html.parser')
    print(int(soup.select('p.no_today > em > span')[0].text.replace(',', '')))

# 사용자 정의 함수

In [ ]:
def BMI(hgt, wgt):
    bmi=wgt / (hgt/100)**2
    return bmi

In [ ]:
BMI(175,86)

In [ ]:
BMI(hgt=175,wgt=86)

In [ ]:
def BMI(hgt=175, wgt=65):
    '''
    이 함수는 무게(kg), 키(cm)에 관한 BMI 함수이다.
    '''
    return wgt / (hgt/100)**2

In [ ]:
BMI()

In [ ]:
def stockPrice(stock):
    res=requests.get(url=f'https://finance.naver.com/item/main.naver?code={stock}')
    soup=bts(markup=res.text, features='html.parser')
    return int(soup.select('p.no_today > em > span')[0].text.replace(',', ''))

In [ ]:
stockPrice(stock='066570')

In [ ]:
for code in codes:
    print(stockPrice(stock=code))
    

## 람다 표현식

In [ ]:
#def BMI(hgt, wgt):
#    bmi=wgt / (hgt/100)**2
#    return bmi

BMI2 = lambda hgt, wgt: wgt / (hgt/100)**2

In [ ]:
BMI2(175,65)

In [ ]:
(lambda hgt, wgt: wgt / (hgt/100)**2)(175,65) # 이렇게 쓸 수도 있다

In [ ]:
sum(range(1, 11))

In [ ]:
def sum(x):
    y=0
    for i in x:
        y-=i
    return y

In [ ]:
sum(range(1, 11))

In [ ]:
%whos

In [ ]:
del sum

In [ ]:
%whos

In [ ]:
def printValue2(*args):
    for i in args:
        print(i)

In [ ]:
printValue2(1,2,3)

In [ ]:
def printValue3(**kwargs):
    for i, v in kwargs.items(): #dictionary로 출력된다 #item는 key와 value를 묶어서 tuple로 출력
        print(f'{i}은(는) {v}입니다')

In [ ]:
printValue3(메뉴 = '순대국', 가격=9000)

In [ ]:
my func.printValue3(메뉴 = '순대국', 가격=9000)

In [8]:
import myfunc1 as mf1

In [9]:
mf1.printValue3(메뉴 = '순대국', 가격=9000)

메뉴은(는) 순대국입니다
가격은(는) 9000입니다


In [10]:
%whos

Variable   Type      Data/Info
------------------------------
mf1        module    <module 'myfunc1' from 'd<...>-main\\live\\myfunc1.py'>
myfunc1    module    <module 'myfunc1' from 'd<...>-main\\live\\myfunc1.py'>


In [11]:
from myfunc1 import printValue3  

In [12]:
printValue3(메뉴 = '순대국', 가격=9000)

메뉴은(는) 순대국입니다
가격은(는) 9000입니다


# Numpy

In [13]:
import numpy as np

In [14]:
ar1=np.array([1,2,3])

In [15]:
ar1

array([1, 2, 3])

In [16]:
# 행 개수, 열 개수
ar1.shape

(3,)

In [17]:
#원소 개수
ar1.size

3

In [18]:
#원소의 자료형(int32는 32비트를 의미)
ar1.dtype

dtype('int32')

In [19]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [ ]:
# numpy의 소원은 통일. numpy는 자료형을 통일시키려고 한다. 

In [20]:
a=[1,2.0,'3']

In [23]:
ar1=np.array(a)

In [24]:
ar1 # numpy는 자료형을 하나로 통일하려는 특성이 있음

array(['1', '2.0', '3'], dtype='<U32')

In [25]:
ar1.astype(float) #실수형으로 바꿔줌

array([1., 2., 3.])

In [27]:
ar1.astype(int) #바로 정수는 바꿀수 없다

ValueError: invalid literal for int() with base 10: '2.0'

In [26]:
ar1.astype(float).astype(int) #체인 메소드 : 여러개 이어서 쓰는 것

array([1, 2, 3])

In [ ]:
#object이면 항상 문자열도 포함되어 있다(문자열로 되어있다 X)

In [28]:
np.array(object=a, dtype='int')

array([1, 2, 3])

In [29]:
np.array(object=a, dtype='float')

array([1., 2., 3.])

In [30]:
np.array(object=a, dtype='int')

array(['1', '2.0', '3'], dtype='<U3')

In [31]:
np.array(object=a, dtype='object') # 문자열도 포함되어 있다

array([1, 2.0, '3'], dtype=object)

In [32]:
#  ★numpy는 통일이지만 pandas는 통일시키지 않는다

In [35]:
np.arange(0,1.1,0.1) #(시작, 끝, 간격)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [37]:
np.linspace(0,1,11) #(시작, 끝, 시작~끝 사이에 들어갈 갯수) <- 얘는 끝값을 포함

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### 원소를 반복한 배열 생성

In [41]:
np.tile(ar1, reps=2)

array(['1', '2.0', '3', '1', '2.0', '3'], dtype='<U32')

In [43]:
np.repeat(ar1, repeats=2)

array(['1', '1', '2.0', '2.0', '3', '3'], dtype='<U32')

In [44]:
np.repeat(ar1, 2) #원소를 두번씩 반복

array(['1', '1', '2.0', '2.0', '3', '3'], dtype='<U32')

In [45]:
np.repeat(ar1, (3,2,1)) #첫번째 3번, 두번쩨 2번, 세번째 1번 반복

array(['1', '1', '1', '2.0', '2.0', '3'], dtype='<U32')

In [46]:
np.repeat(ar1, range(3,0,-1))

array(['1', '1', '1', '2.0', '2.0', '3'], dtype='<U32')

### 1차원 배열 인덱싱 및 슬라이싱

In [47]:
ar1=np.arange(1,12,2)

In [48]:
ar1

array([ 1,  3,  5,  7,  9, 11])

In [49]:
ar1[0] #indexing을 하면 원소의 자료형으로 나온다

1

In [51]:
ar1[-1]

11

In [53]:
ar1[1:5] #어레이로 나옴

array([3, 5, 7, 9])

In [54]:
ar1[[3,2,1]] #list는 배열 indexing이 안됬음

array([7, 5, 3])

In [55]:
#np.arange()
ar1[np.arange(3,0,-1)]

array([7, 5, 3])

In [57]:
#np.tile
ar1[np.tile(3,3)]

array([7, 7, 7])

## 2차원 배열 생성

In [60]:
ar2=np.array([[1,2,3],[4,5,6]])

In [61]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
print(ar2)

[[1 2 3]
 [4 5 6]]


In [63]:
ar2.shape

(2, 3)

In [64]:
ar2.size

6

In [65]:
ar2.dtype

dtype('int32')

In [66]:
ar1=np.arange(0,12)

In [67]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
ar1.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
ar1.reshape(4,3,order='F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [70]:
ar2ar2

NameError: name 'ar2ar2' is not defined

In [76]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
ar2.flatten()

array([1, 2, 3, 4, 5, 6])

In [82]:
ar2.flatten()

array([1, 2, 3, 4, 5, 6])

In [83]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
ar2[1,1]

5

In [90]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [91]:
ar2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [93]:
ar2[:,1:3]

array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12]])

In [94]:
ar2[:,[2,1]]

array([[ 3,  2],
       [ 6,  5],
       [ 9,  8],
       [12, 11]])

In [95]:
ar2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [101]:
ar2[:, 2]*2

array([ 6, 12, 18, 24])

In [103]:
ar2[:, 2]

array([ 3,  6,  9, 12])

## [참고] 수학 관련 값과 함수(p123)

In [104]:
# 자연상수(2.7182)를 반환합니다.
np.e

2.718281828459045

In [105]:
# 파이(3.141592)를 반환합니다.
np.pi

3.141592653589793

In [106]:
# 결측값을 반환합니다.
np.nan #NA : not available 결측 missing value / NaN : Not a Number 수치 결측(자료형이 실수이다)
#NULL : 애초에 정의되지 않은 상태

nan

In [109]:
type(np.nan)

float

In [108]:
# 무한대를 반환합니다.
np.inf

inf

In [110]:
# 소수점을 버립니다.
np.floor(np.e) #e=2.718....

2.0

In [111]:
# 소수점을 올립니다.
np.ceil(np.pi)

4.0

In [112]:
# 소수점 둘째자리까지 남도록 반올림합니다.
np.round(np.e, 2)

2.72

In [113]:
# 제곱근을 반환합니다.
np.sqrt(4)

2.0

In [114]:
# 거듭제곱을 반환합니다.
np.power(2, 3)

8

In [115]:
# 자연상수 거듭제곱을 반환합니다.
np.exp(1)

2.718281828459045

In [116]:
# 자연로그를 반환합니다.
np.log(10)

2.302585092994046

In [117]:
# 모든 원소를 더합니다.
np.sum(ar1)

66

In [120]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [119]:
# 모든 원소를 곱합니다.
np.prod(ar1)

0

In [121]:
# 원소의 차이를 반환합니다.
np.diff(ar1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [122]:
# ★최솟값을 반환합니다.
np.min(ar1)

0

In [123]:
# ★최댓값을 반환합니다.
np.max(ar1)

11

In [124]:
# ★평균을 반환합니다.
np.mean(ar1)

5.5

In [125]:
# ★중위수를 반환합니다.
np.median(ar1)

5.5

In [127]:
#★ 분산을 반환합니다.
np.var(ar1)

11.916666666666666

In [128]:
#★표준편차를 반환합니다.
np.std(ar1)

3.452052529534663

In [129]:
# ★원소 개수를 반환합니다.
np.size(ar1)

12

# PANDAS 라이브러리

In [130]:
#2010년경 만들어짐(금융쪽에서)
#pandas : panel

In [131]:
import pandas as pd

In [132]:
# 행이나 열을 선택하면 시리즈가 된다

In [133]:
# P127 중요
# 음식 : 메뉴 -> 재료 -> 손질 -> 조리 -> 플레이팅 -> 먹기
# 분석 : 주제 -> 데이터 -> 전처리 -> 모형 -> 리포팅 -> 활용

In [134]:
# 데이터프레임의 원소를 열!!!!!
# 데이터프레임 각각의 값을 cell값

In [136]:
ar1=np.arange(1,6,2)

In [137]:
ar1

array([1, 3, 5])

In [143]:
sr=pd.Series(data=ar1)
sr # 0,1,2가 인덱스이고 1,3,5가 값이다

0    1
1    3
2    5
dtype: int32

In [144]:
type(sr)

pandas.core.series.Series

In [145]:
#numpy는 가로 출력, pandas는 세로 출력

In [147]:
sr1=pd.Series(data=[1,2.0,'3'], index=['a','b','c'])
sr1

a      1
b    2.0
c      3
dtype: object

In [149]:
for i in sr1:
    print(type(i)) #'가 없다고 문자열이 아닌것은 아니다

<class 'int'>
<class 'float'>
<class 'str'>


In [150]:
sr1 + 1 # 문자열에 1을 더할 수 없다

TypeError: can only concatenate str (not "int") to str

In [153]:
sr1.astype(int) +1

a    2
b    3
c    4
dtype: int32

In [154]:
sr1.astype(str)+'1'

a      11
b    2.01
c      31
dtype: object

In [166]:
sr2=pd.Series(data={'a':1, 'b':2, 'c':5}) #dict로 data 프레임을 만들면 key가 index가 된다(따라서 index를 따로 쓰면 안된다)
sr2

a    1
b    2
c    5
dtype: int64

In [159]:
sr

0    1
1    3
2    5
dtype: int32

In [160]:
sr.shape

(3,)

In [161]:
sr.size

3

In [162]:
sr.dtype

dtype('int32')

In [163]:
sr.values

array([1, 3, 5])

In [164]:
sr.index

RangeIndex(start=0, stop=3, step=1)

In [165]:
sr1.index 

Index(['a', 'b', 'c'], dtype='object')

In [167]:
sr2.index

Index(['a', 'b', 'c'], dtype='object')

### index 변환 및 type 확인

In [169]:
type(sr.index)

pandas.core.indexes.range.RangeIndex

In [170]:
sr.index=[1,2,3]

In [171]:
sr

1    1
2    3
3    5
dtype: int32

In [172]:
type(sr.index)

pandas.core.indexes.numeric.Int64Index

In [173]:
sr.index=['a','b','c']

In [174]:
sr

a    1
b    3
c    5
dtype: int32

In [175]:
type(sr.index)

pandas.core.indexes.base.Index

In [176]:
#★★★★★★★★★★★★시리즈의 index는 이름이다(위치 번호가 아니다)

In [178]:
sr

a    1
b    3
c    5
dtype: int32

In [ ]:
#iloc integer loc -> 정수 index로 원소를 선택한다

In [179]:
sr

a    1
b    3
c    5
dtype: int32

In [180]:
sr.iloc[0]

1

In [181]:
sr.iloc[0:2]

a    1
b    3
dtype: int32

In [183]:
sr.iloc[[0]]

a    1
dtype: int32

In [184]:
sr.iloc[[0,2]]

a    1
c    5
dtype: int32

In [185]:
sr.loc['a'] # <- 보이는 그래도의 index가 들어간다 / 행이름 인덱스

1

In [186]:
sr.loc[['a']]

a    1
dtype: int32

In [187]:
sr.loc[['a','c']]

a    1
c    5
dtype: int32

In [189]:
sr.loc['a':'c'] # 마지막 꺼를 포함한다

a    1
b    3
c    5
dtype: int32

In [207]:
sr3=pd.Series(data=range(3), index=range(1,4))

In [194]:
sr3

1    0
2    1
3    2
dtype: int64

In [195]:
sr3.iloc[0]

0

In [196]:
sr3.loc[1]

0

In [199]:
sr4=pd.Series(data=range(3), index=np.tile(1,3))

In [200]:
sr4

1    0
1    1
1    2
dtype: int64

In [201]:
sr4.iloc[0]

0

In [202]:
sr4.loc[1]

1    0
1    1
1    2
dtype: int64

In [210]:
sr3

1    0
2    1
3    2
dtype: int64

In [208]:
sr3 >=1

1    False
2     True
3     True
dtype: bool

In [212]:
sr3

1    0
2    1
3    2
dtype: int64

In [206]:
sr3.loc[sr3>=1] #불린형 인덱싱

1    1
1    2
dtype: int64

In [213]:
sr.loc[(sr >=1) & (sr < 3)]

a    1
dtype: int32

In [214]:
sr

a    1
b    3
c    5
dtype: int32

In [220]:
sr

a    1
b    3
c    5
dtype: int32

In [216]:
(sr >=1) & (sr < 3) #시리즈에 대해서는 논리연산자(and, or ..) 못쓴다 -> &,| 이런거 쓴다

a     True
b    False
c    False
dtype: bool

In [217]:
(sr >=1) | (sr < 3)

a    True
b    True
c    True
dtype: bool

In [218]:
(sr >=1) ^ (sr < 3)

a    False
b     True
c     True
dtype: bool

In [219]:
~(sr >=1)

a    False
b    False
c    False
dtype: bool

### 얕은 복사 vs 깊은 복사

In [ ]:
# 얕은 복사 : 원본이랑 같이 변함
# 깊은 복사 : copy사용. 백업으로 사용 가능(원본이랑 같이 변하지 않음. 저장id가 다름)

In [221]:
sr1

a      1
b    2.0
c      3
dtype: object

In [222]:
sr4=sr1

In [223]:
sr4

a      1
b    2.0
c      3
dtype: object

In [224]:
sr4.loc['a']=2

In [225]:
sr4

a      2
b    2.0
c      3
dtype: object

In [226]:
sr1

a      2
b    2.0
c      3
dtype: object

In [227]:
id(sr1)

2201031270000

In [228]:
id(sr4)

2201031270000

In [229]:
sr5=sr1.copy() # 깊은 복사

In [230]:
sr5

a      2
b    2.0
c      3
dtype: object

In [231]:
sr5.loc['a']=1

In [232]:
sr5

a      1
b    2.0
c      3
dtype: object

In [233]:
sr1

a      2
b    2.0
c      3
dtype: object

In [234]:
id(sr5)

2201067334304

In [235]:
id(sr1)

2201031270000

### 데이터프레임 생성

In [ ]:
#변수명 생성
#ex. number of cout
#  방법1. camel case : numberOfCount(현재 개발자가 많이 사용)
#  방법2. pascal case : NumverOfCount
#  방법3. snake case : number_of_count

In [237]:
ar2=np.arange(1,7)
ar2

array([1, 2, 3, 4, 5, 6])

In [238]:
ar2=np.arange(1,7).reshape(3,-1)
ar2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [239]:
df=pd.DataFrame(data=ar2)

In [240]:
df

0  1
0  1  2
1  3  4
2  5  6

In [241]:
type(df)

pandas.core.frame.DataFrame

In [244]:
df=pd.DataFrame(data=ar2, index=range(1,4), columns=['A','B'])
df

A  B
1  1  2
2  3  4
3  5  6

In [248]:
import requests 
from bs4 import BeautifulSoup as bts

def stockPrice(stock):
    res=requests.get(url=f'https://finance.naver.com/item/main.naver?code={stock}')
    soup=bts(markup=res.text, features='html.parser')
    return int(soup.select('p.no_today > em > span')[0].text.replace(',', ''))

In [249]:
codes=['066570', '005930', '000660']

In [250]:
price=[stockPrice(stock=code) for code in codes]

In [251]:
price

[94000, 56800, 93000]

In [256]:
pd.DataFrame(data={'종목코드': codes, '현재가격': price})

종목코드   현재가격
0  066570  94000
1  005930  56800
2  000660  93000

In [257]:
df.shape

(3, 2)

In [258]:
df.shape[0]

3

In [259]:
df.dtypes

A    int32
B    int32
dtype: object

In [260]:
df.values

array([[1, 2],
       [3, 4],
       [5, 6]])

In [261]:
df.index

RangeIndex(start=1, stop=4, step=1)

In [262]:
df.columns

Index(['A', 'B'], dtype='object')

In [263]:
df.info() #괄호 써야한다

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 1 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int32
 1   B       3 non-null      int32
dtypes: int32(2)
memory usage: 156.0 bytes


In [ ]:
# df는 DataFrame이다
# .......

### loc, iloc

In [264]:
df.iloc[0]

A    1
B    2
Name: 1, dtype: int32

In [265]:
df.iloc[[0]]

A  B
1  1  2

In [266]:
df.iloc[0, :]

A    1
B    2
Name: 1, dtype: int32

In [270]:
df.iloc[1, :]

A    3
B    4
Name: 2, dtype: int32

In [271]:
df.iloc[0:2, 0:2]

A  B
1  1  2
2  3  4

In [272]:
df

A  B
1  1  2
2  3  4
3  5  6

In [273]:
df.loc[1]

A    1
B    2
Name: 1, dtype: int32

In [274]:
df.loc[[1]]

A  B
1  1  2

In [275]:
df.loc[[1,3]]

A  B
1  1  2
3  5  6

In [276]:
df.loc[1:3]

A  B
1  1  2
2  3  4
3  5  6

In [277]:
df.loc[1:3, :]

A  B
1  1  2
2  3  4
3  5  6

In [278]:
df.loc[:,'A':'B']

A  B
1  1  2
2  3  4
3  5  6

In [280]:
df.loc[[2],['A']]

A
2  3

In [282]:
df.iloc[[1],[0]]

A
2  3